version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    networks:
      - laihe-network

networks:
  laihe-network:
    driver: bridge 